### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by g3wanghc** [Developers-Foundation/tse#2]
Create blank placeholder components that can used to fill content for future use.

**Comment by g3wanghc** [comment]
Proposed design can be found in google drive.

**Comment by g3wanghc** [comment]
@BrandenSoropia I'm getting weird results when I'm running it on my computer. 

![image](https://cloud.githubusercontent.com/assets/7648872/26524177/cb0f1aa0-42df-11e7-9f65-b2db4245fbd3.png)

**Comment by g3wanghc** [comment]
Please refer to the Layouts in the [Google Drive](https://drive.google.com/drive/u/0/folders/0BxZbhESPG6oqY1lJd3ZBVmZFQ3c).

**Comment by BrandenSoropia** [comment]
You only said to create empty placeholders and divs. I was supposed to style it like the layout as well?

**Comment by g3wanghc** [comment]
Oh haha my bad, I meant the layouts as well hopefully. Or do you think its better to make a separate ticket for that?

**Comment by g3wanghc** [comment]
Code in be676964b412ae59af5e597ccb79ef7c94ccd225
